[BUG #5788] Publish portable Testrunner

diff --git a/tool/admin/release/Makefile.release b/tool/admin/release/Makefile.release
--- a/tool/admin/release/Makefile.release
+++ b/tool/admin/release/Makefile.release
@@ -288,7 +288,14 @@ build-apps:
 	done
 
 build-components:
-	@time for APPLICATION in $(COMPONENTS); do ( cd component/$$APPLICATION && $(CMD_GENERATOR) build ) || exit 1; done
+	@time for APPLICATION in $(COMPONENTS); do \
+		if [ "$$APPLICATION" = "testrunner" ]; then \
+			( cd component/$$APPLICATION && $(CMD_GENERATOR) build ) || exit 1; \
+			( cd component/$$APPLICATION && $(CMD_GENERATOR) -c portable.json build ) || exit 1; \
+		else \
+			( cd component/$$APPLICATION && $(CMD_GENERATOR) build ) || exit 1; \
+		fi; \
+	done
 
 build-framework:
 	@for TARGET in $(FRAMEWORK_TARGETS); do ( cd framework && $(CMD_GENERATOR) $$TARGET ) || exit 1; done
@@ -362,6 +369,13 @@ check-components:
 		if [ "$$TARGET" = "inspector" ]; then \
 			F="component/$$TARGET/build/script/$$TARGET.js"; \
 			[ -s $$F ] || ( echo "Missing $$F; run 'make publish-build' first!"; exit 1 ); \
+		elif [ "$$TARGET" = "testrunner" ]; then \
+			F="component/$$TARGET/build/script/$$TARGET.js"; \
+			[ -s $$F ] || ( echo "Missing $$F; run 'make publish-build' first!"; exit 1 ); \
+			F="component/$$TARGET/build/script/$$TARGET-portable.js"; \
+			[ -s $$F ] || ( echo "Missing $$F; run 'make publish-build' first!"; exit 1 ); \
+		else \
+			F="component/$$TARGET/build/script"; [ -d $$F ] || ( echo "Missing $$F; run 'make publish-build' first!"; exit 1 ); \
 		fi; \
 	done
 
@@ -403,6 +417,9 @@ publish-apps:
 		if [ "$$APPLICATION" = "inspector" ]; then \
 			echo "    - $$APPLICATION..."; \
 			$(CMD_SYNC_ONLINE) component/$$APPLICATION/build/* $(STAGING_HOST):/var/www/qooxdoo/demo/$(FRAMEWORK_VERSION)/$$APPLICATION || exit 1; \
+		elif [ "$$APPLICATION" = "testrunner" ]; then \
+			echo "    - $$APPLICATION..."; \
+			$(CMD_SYNC_ONLINE) component/$$APPLICATION/build/testrunner-portable.js $(STAGING_HOST):/var/www/qooxdoo/demo/$(FRAMEWORK_VERSION)/$$APPLICATION || exit 1; \
 		fi; \
 	done
 	@echo "  * Syncing framework..."
