Build testrunner-portable with the applications since components aren't published with the devel demos

diff --git a/tool/admin/release/Makefile.release b/tool/admin/release/Makefile.release
--- a/tool/admin/release/Makefile.release
+++ b/tool/admin/release/Makefile.release
@@ -68,7 +68,7 @@ CMD_SYNC_BACKUP = $(CMD_NICE) rsync --recursive --delete --inplace --copy-links 
 RELEASE_BUILD = release/temp/build/qooxdoo-$(FRAMEWORK_VERSION)-build
 RELEASE_SDK = release/temp/sdk/qooxdoo-$(FRAMEWORK_VERSION)-sdk
 
-APPLICATIONS = todo feedreader portal mobileshowcase playground showcase widgetbrowser featureconfigeditor demobrowser
+APPLICATIONS = todo feedreader portal mobileshowcase playground showcase widgetbrowser featureconfigeditor demobrowser testrunner-portable
 COMPONENTS = apiviewer testrunner inspector
 FRAMEWORK_TARGETS = api test qxoo-build qxoo-noopt
 
@@ -282,20 +282,15 @@ build-apps:
 	@time for APPLICATION in $(APPLICATIONS); do \
 		if [ "$$APPLICATION" = "feedreader" ]; then \
 			( cd application/$$APPLICATION && $(CMD_GENERATOR) build,build-mobile,build-website ) || exit 1; \
+		elif [ "$$APPLICATION" = "testrunner-portable" ]; then \
+			( cd component/testrunner && $(CMD_GENERATOR) -c portable.json build ) || exit 1; \
 		else \
 			( cd application/$$APPLICATION && $(CMD_GENERATOR) build ) || exit 1; \
 		fi; \
 	done
 
 build-components:
-	@time for APPLICATION in $(COMPONENTS); do \
-		if [ "$$APPLICATION" = "testrunner" ]; then \
-			( cd component/$$APPLICATION && $(CMD_GENERATOR) build ) || exit 1; \
-			( cd component/$$APPLICATION && $(CMD_GENERATOR) -c portable.json build ) || exit 1; \
-		else \
-			( cd component/$$APPLICATION && $(CMD_GENERATOR) build ) || exit 1; \
-		fi; \
-	done
+	@time for APPLICATION in $(COMPONENTS); do ( cd component/$$APPLICATION && $(CMD_GENERATOR) build ) || exit 1; done
 
 build-framework:
 	@for TARGET in $(FRAMEWORK_TARGETS); do ( cd framework && $(CMD_GENERATOR) $$TARGET ) || exit 1; done
@@ -356,12 +351,15 @@ check-banner:
 
 check-apps:
 	@for TARGET in $(APPLICATIONS); do \
-    if [ "$$TARGET" = "featureconfigeditor" ] ; then \
-      F="application/$$TARGET/build/script/fce.js"; \
-    else \
-      F="application/$$TARGET/build/script/$$TARGET.js"; \
-    fi; \
-    [ -s $$F ] || [ "$$TARGET" = "widgetbrowser" ] || ( echo "Missing $$F; run 'make publish-build' first!"; exit 1 ); \
+	if [ "$$TARGET" = "featureconfigeditor" ] ; then \
+		F="application/$$TARGET/build/script/fce.js"; \
+	elif [ "$$TARGET" = "testrunner-portable" ] ; then \
+		F="component/testrunner/build/script/$$TARGET.js"; \
+		[ -s $$F ] || ( echo "Missing $$F; run 'make publish-build' first!"; exit 1 ); \
+	else \
+		F="application/$$TARGET/build/script/$$TARGET.js"; \
+	fi; \
+	[ -s $$F ] || [ "$$TARGET" = "widgetbrowser" ] || ( echo "Missing $$F; run 'make publish-build' first!"; exit 1 ); \
   done
 
 check-components:
@@ -372,10 +370,6 @@ check-components:
 		elif [ "$$TARGET" = "testrunner" ]; then \
 			F="component/$$TARGET/build/script/$$TARGET.js"; \
 			[ -s $$F ] || ( echo "Missing $$F; run 'make publish-build' first!"; exit 1 ); \
-			F="component/$$TARGET/build/script/$$TARGET-portable.js"; \
-			[ -s $$F ] || ( echo "Missing $$F; run 'make publish-build' first!"; exit 1 ); \
-		else \
-			F="component/$$TARGET/build/script"; [ -d $$F ] || ( echo "Missing $$F; run 'make publish-build' first!"; exit 1 ); \
 		fi; \
 	done
 
@@ -404,12 +398,16 @@ publish-apps:
 	@echo "  * Syncing applications..."
 	@for APPLICATION in $(APPLICATIONS); do \
 		echo "    - $$APPLICATION..."; \
-		$(CMD_SYNC_ONLINE) application/$$APPLICATION/build/* $(STAGING_HOST):/var/www/qooxdoo/demo/$(FRAMEWORK_VERSION)/$$APPLICATION || exit 1; \
 		if [ "$$APPLICATION" = "feedreader" ]; then \
 			echo "    - $$APPLICATION-mobile..."; \
+			$(CMD_SYNC_ONLINE) application/$$APPLICATION/build/* $(STAGING_HOST):/var/www/qooxdoo/demo/$(FRAMEWORK_VERSION)/$$APPLICATION || exit 1; \
 			$(CMD_SYNC_ONLINE) application/$$APPLICATION/build-mobile/* $(STAGING_HOST):/var/www/qooxdoo/demo/$(FRAMEWORK_VERSION)/$$APPLICATION-mobile || exit 1; \
 			echo "    - $$APPLICATION-website..."; \
 			$(CMD_SYNC_ONLINE) application/$$APPLICATION/build-website/* $(STAGING_HOST):/var/www/qooxdoo/demo/$(FRAMEWORK_VERSION)/$$APPLICATION-website || exit 1; \
+		elif [ "$$APPLICATION" = "testrunner-portable" ]; then \
+			$(CMD_SYNC_ONLINE) component/testrunner/build/script/$$APPLICATION.js $(STAGING_HOST):/var/www/qooxdoo/demo/$(FRAMEWORK_VERSION)/$$APPLICATION || exit 1; \
+		else \
+			$(CMD_SYNC_ONLINE) application/$$APPLICATION/build/* $(STAGING_HOST):/var/www/qooxdoo/demo/$(FRAMEWORK_VERSION)/$$APPLICATION || exit 1; \
 		fi; \
 	done
 	@echo "  * Syncing components..."
@@ -417,9 +415,6 @@ publish-apps:
 		if [ "$$APPLICATION" = "inspector" ]; then \
 			echo "    - $$APPLICATION..."; \
 			$(CMD_SYNC_ONLINE) component/$$APPLICATION/build/* $(STAGING_HOST):/var/www/qooxdoo/demo/$(FRAMEWORK_VERSION)/$$APPLICATION || exit 1; \
-		elif [ "$$APPLICATION" = "testrunner" ]; then \
-			echo "    - $$APPLICATION..."; \
-			$(CMD_SYNC_ONLINE) component/$$APPLICATION/build/script/testrunner-portable.js $(STAGING_HOST):/var/www/qooxdoo/demo/$(FRAMEWORK_VERSION)/$$APPLICATION || exit 1; \
 		fi; \
 	done
 	@echo "  * Syncing framework..."
