integrated Website into build process and index.html

diff --git a/tool/admin/release/Makefile.release b/tool/admin/release/Makefile.release
--- a/tool/admin/release/Makefile.release
+++ b/tool/admin/release/Makefile.release
@@ -76,7 +76,7 @@ RELEASE_BUILD = release/temp/build/qooxdoo-$(FRAMEWORK_VERSION)-build
 RELEASE_SDK = release/temp/sdk/qooxdoo-$(FRAMEWORK_VERSION)-sdk
 
 APPLICATIONS = todo feedreader portal mobileshowcase playground showcase widgetbrowser featureconfigeditor demobrowser
-COMPONENTS = apiviewer testrunner inspector storage server
+COMPONENTS = apiviewer testrunner inspector storage server website
 FRAMEWORK_TARGETS = api test
 
 
@@ -293,11 +293,19 @@ build-apps:
 
 build-components:
 	@time for COMPONENT in $(COMPONENTS); do \
-		( cd component/$$COMPONENT && $(CMD_GENERATOR) build ) || exit 1; \
 		if [ "$$COMPONENT" = "storage" ]; then \
+			( cd component/standalone/$$COMPONENT && $(CMD_GENERATOR) build ) || exit 1; \
 			( cd component/standalone/$$COMPONENT && $(CMD_GENERATOR) build-require ) || exit 1; \
+		elif [ "$$COMPONENT" = "website" ]; then \
+			( cd component/standalone/$$COMPONENT && $(CMD_GENERATOR) build ) || exit 1; \
+			( cd component/standalone/$$COMPONENT && $(CMD_GENERATOR) build-min ) || exit 1; \
+		elif [ "$$COMPONENT" = "server" ]; then \
+			( cd component/standalone/$$COMPONENT && $(CMD_GENERATOR) build ) || exit 1; \
 		elif [ "$$COMPONENT" = "testrunner" ]; then \
+			( cd component/$$COMPONENT && $(CMD_GENERATOR) build ) || exit 1; \
 			( cd component/testrunner && $(CMD_GENERATOR) -c portable.json build ) || exit 1; \
+		else \
+			( cd component/$$COMPONENT && $(CMD_GENERATOR) build ) || exit 1; \
 		fi; \
 	done
 
@@ -365,6 +373,8 @@ publish-build-components:
 	@( cd component/testrunner && $(CMD_GENERATOR) -c portable.json build ) || exit 1;
 	@( cd component/standalone/storage && $(CMD_GENERATOR) build ) || exit 1
 	@( cd component/standalone/storage && $(CMD_GENERATOR) build-require ) || exit 1
+	@( cd component/standalone/website && $(CMD_GENERATOR) build ) || exit 1
+	@( cd component/standalone/website && $(CMD_GENERATOR) build-min ) || exit 1
 	@( cd component/standalone/server && $(CMD_GENERATOR) source ) || exit 1
 	@( cd component/standalone/server && $(CMD_GENERATOR) build ) || exit 1
 
@@ -400,6 +410,11 @@ check-components:
 			F="component/standalone/$$TARGET/script/$$TARGET.js"; \
 			[ -s $$F ] || ( echo "Missing $$F; run 'make publish-build' first!"; exit 1 ); \
 			F="component/standalone/$$TARGET/script/$$TARGET-require.js"; \
+			[ -s $$F ] || ( echo "Missing $$F; run 'make publish-build' first!"; exit 1 ); \
+		elif [ "$$TARGET" = "website" ]; then \
+			F="component/standalone/$$TARGET/script/q.js"; \
+			[ -s $$F ] || ( echo "Missing $$F; run 'make publish-build' first!"; exit 1 ); \
+			F="component/standalone/$$TARGET/script/q.min.js"; \
 			[ -s $$F ] || ( echo "Missing $$F; run 'make publish-build' first!"; exit 1 ); \
 		elif [ "$$TARGET" = "server" ]; then \
 			F="component/standalone/$$TARGET/script/qx-oo.js"; \
@@ -474,6 +489,10 @@ publish-apps:
 			echo "    - $$COMPONENT..."; \
 			$(CMD_SYNC_ONLINE) component/standalone/$$COMPONENT/script/$$COMPONENT.js $(STAGING_HOST):/var/www/qooxdoo/demo/$(FRAMEWORK_VERSION)/framework || exit 1; \
 			$(CMD_SYNC_ONLINE) component/standalone/$$COMPONENT/script/$$COMPONENT-require.js $(STAGING_HOST):/var/www/qooxdoo/demo/$(FRAMEWORK_VERSION)/framework || exit 1; \
+		elif [ "$$COMPONENT" = "website" ]; then \
+			echo "    - $$COMPONENT..."; \
+			$(CMD_SYNC_ONLINE) component/standalone/$$COMPONENT/script/q.js $(STAGING_HOST):/var/www/qooxdoo/demo/$(FRAMEWORK_VERSION)/framework || exit 1; \
+			$(CMD_SYNC_ONLINE) component/standalone/$$COMPONENT/script/q.min.js $(STAGING_HOST):/var/www/qooxdoo/demo/$(FRAMEWORK_VERSION)/framework || exit 1; \
 		elif [ "$$COMPONENT" = "server" ]; then \
 			$(CMD_SYNC_ONLINE) component/standalone/$$COMPONENT/script/qx-oo.js $(STAGING_HOST):/var/www/qooxdoo/demo/$(FRAMEWORK_VERSION)/framework || exit 1; \
 			$(CMD_SYNC_ONLINE) component/standalone/$$COMPONENT/script/qx-oo-noopt.js $(STAGING_HOST):/var/www/qooxdoo/demo/$(FRAMEWORK_VERSION)/framework || exit 1; \
