[BUG #4790] Generate mobile version of Feedreader
git-svn-id: https://qooxdoo.svn.sourceforge.net/svnroot/qooxdoo/trunk@26052 61aaf1ca-a10e-0410-b9fb-ac63ec25887f

diff --git a/qooxdoo/tool/admin/release/Makefile.release b/qooxdoo/tool/admin/release/Makefile.release
--- a/qooxdoo/tool/admin/release/Makefile.release
+++ b/qooxdoo/tool/admin/release/Makefile.release
@@ -238,7 +238,13 @@ distclean:
 
 build: build-apps build-components
 build-apps:
-	@time for APPLICATION in $(APPLICATIONS); do ( cd application/$$APPLICATION && $(CMD_GENERATOR) build ) || exit 1; done
+	@time for APPLICATION in $(APPLICATIONS); do \
+		if [ "$$APPLICATION" = "feedreader" ]; then \
+			( cd application/$$APPLICATION && $(CMD_GENERATOR) build,build-mobile ) || exit 1; \
+		else \
+			( cd application/$$APPLICATION && $(CMD_GENERATOR) build ) || exit 1; \
+		fi; \
+	done
 
 build-components:
 	@time for APPLICATION in $(COMPONENTS); do ( cd component/$$APPLICATION && $(CMD_GENERATOR) build ) || exit 1; done
@@ -249,6 +255,13 @@ build-framework:
 source: source-apps source-components
 source-apps:
 	@time for APPLICATION in $(APPLICATIONS); do ( cd application/$$APPLICATION && $(CMD_GENERATOR) source ) || exit 1; done
+	@time for APPLICATION in $(APPLICATIONS); do \
+		if [ "$$APPLICATION" = "feedreader" ]; then \
+			( cd application/$$APPLICATION && $(CMD_GENERATOR) source,source-mobile ) || exit 1; \
+		else \
+			( cd application/$$APPLICATION && $(CMD_GENERATOR) source ) || exit 1; \
+		fi; \
+	done
 
 source-components:
 	@time for APPLICATION in $(COMPONENTS); do ( cd component/$$APPLICATION && $(CMD_GENERATOR) source ) || exit 1; done
@@ -298,11 +311,11 @@ check-apps:
 
 check-components:
 	@for TARGET in $(COMPONENTS); do \
-     if [ "$$TARGET" = "inspector" ]; then \
-       F="component/$$TARGET/build/script/$$TARGET.js"; \
-       [ -s $$F ] || ( echo "Missing $$F; run 'make publish-build' first!"; exit 1 ); \
-     fi; \
-  done
+		if [ "$$TARGET" = "inspector" ]; then \
+			F="component/$$TARGET/build/script/$$TARGET.js"; \
+			[ -s $$F ] || ( echo "Missing $$F; run 'make publish-build' first!"; exit 1 ); \
+		fi; \
+	done
 
 check-framework:
 	@for TARGET in $(FRAMEWORK_TARGETS); do \
