fixed broken app check for featureconfigeditor
git-svn-id: https://qooxdoo.svn.sourceforge.net/svnroot/qooxdoo/trunk@28085 61aaf1ca-a10e-0410-b9fb-ac63ec25887f

diff --git a/qooxdoo/tool/admin/release/Makefile.release b/qooxdoo/tool/admin/release/Makefile.release
--- a/qooxdoo/tool/admin/release/Makefile.release
+++ b/qooxdoo/tool/admin/release/Makefile.release
@@ -325,7 +325,14 @@ check-banner:
 	@echo "  * Checking kit is complete..."
 
 check-apps:
-	@for TARGET in $(APPLICATIONS); do F="application/$$TARGET/build/script/$$TARGET.js"; [ -s $$F ] || [ "$$TARGET" = "widgetbrowser" ] || ( echo "Missing $$F; run 'make publish-build' first!"; exit 1 ); done
+	@for TARGET in $(APPLICATIONS); do \
+    if [ "$$TARGET" = "featureconfigeditor" ] ; then \
+      F="application/$$TARGET/build/script/fce.js"; \
+    else \
+      F="application/$$TARGET/build/script/$$TARGET.js"; \
+    fi; \
+    [ -s $$F ] || [ "$$TARGET" = "widgetbrowser" ] || ( echo "Missing $$F; run 'make publish-build' first!"; exit 1 ); \
+  done
 
 check-components:
 	@for TARGET in $(COMPONENTS); do \
